name: CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Setup Gradle and execute tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: 7.4.2